"""
Django settings for Rasayam_website project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url  # For parsing unified cloud database URLs

# Load environment variables from .env file (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--kmib+28jls)_o*vi!288xd&me=4)64#pli0y!(vhp+g&3-msr')

# SECURITY WARNING: don't run with debug turned on in production!
# Automatically handles True locally and False on Render when configured in dashboard env variables
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Secure host bindings for local servers and production endpoints
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
else:
    ALLOWED_HOSTS.append('*')  # Fallback for dynamic preview links if needed


# Application definition
INSTALLED_APPS = [
    "unfold",  # <--- THIS MUST BE FIRST
    "unfold.contrib.filters",  # For better sidebar filters
    "unfold.contrib.forms",    # For modern form layouts
    "unfold.contrib.import_export",  # For bulk upload feature

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'cloudinary_storage',
    'cloudinary',
    "import_export",

    'products',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Efficient static file server for production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Rasayam_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # --- Rasayam Custom Processors ---
                'products.context_processors.cart_count', 
            ],
        },
    },
]

WSGI_APPLICATION = 'Rasayam_website.wsgi.application'


# ==========================================
# DATABASE CONFIGURATION
# ==========================================
# Seamlessly checks for a unified cloud connection string first (Render/Neon).
# Falls back directly to split local variable keys if a single string isn't present.
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif not RENDER_EXTERNAL_HOSTNAME and os.getenv('USE_POSTGRES') != 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif os.getenv('DB_NAME') and os.getenv('DB_USER'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==========================================
# STATIC & MEDIA FILES CONFIGURATION
# ==========================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 🚫 REMOVE OR COMMENT OUT THIS ENTIRE BLOCK BELOW:
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# Cloudinary Credentials
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}

# Modern Django Storage Configuration
IS_TESTING = 'test' in sys.argv
STATICFILES_BACKEND = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG or IS_TESTING
    else "whitenoise.storage.CompressedStaticFilesStorage"
)

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": STATICFILES_BACKEND,
    },
}

# Safe fallback protection rule
WHITENOISE_MANIFEST_STRICT = False

# ==========================================
# THIRD-PARTY & CUSTOM SETTINGS
# ==========================================

# Razorpay Keys
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')

LOGIN_URL = 'login'

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "RASAYAM Admin",
    "SITE_HEADER": "RASAYAM Business Portal",
    "SHOW_HISTORY": True,
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False, 
        "navigation": [
            {
                "title": "Marketing & Storefront",
                "items": [
                    {
                        "title": "Banners",
                        "icon": "image", 
                        "link": "/admin/products/banner/",
                    },
                    {
                        "title": "Promo Boxes",
                        "icon": "featured_video",
                        "link": "/admin/products/promobox/",
                    },
                ],
            },
            {
                "title": "Inventory Management",
                "items": [
                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": "/admin/products/product/",
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/products/category/",
                    },
                ],
            },
            {
                "title": "Sales & Support",
                "items": [
                    {
                        "title": "Orders",
                        "icon": "shopping_cart",
                        "link": "/admin/products/order/",
                    },
                    {
                        "title": "Customer Profiles",
                        "icon": "person",
                        "link": "/admin/products/customerprofile/",
                    },
                    {
                        "title": "Contact Inquiries",
                        "icon": "mail",
                        "link": "/admin/products/contactinquiry/",
                    },
                    {
                        "title": "Product Reviews",
                        "icon": "star",
                        "link": "/admin/products/review/",
                    },
                ],
            },
        ],
    },
}

# Prevents WhiteNoise from crashing during local development and testing if an asset is missing
WHITENOISE_MANIFEST_STRICT = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not DEBUG and (not RAZORPAY_KEY_ID or not RAZORPAY_KEY_SECRET):
    raise ValueError("Production requires RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET")
