"""
Django settings for Rasayam_website project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url  # For parsing unified cloud database URLs

# Load environment variables from .env file (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=None):
    value = os.getenv(name)
    if not value:
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
DEBUG = env_bool('DEBUG', default=True)
STRICT_PRODUCTION_ENV = env_bool('STRICT_PRODUCTION_ENV', default=False)

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-development-only-change-in-production'
    else:
        raise ValueError('Production requires SECRET_KEY to be set.')

# Hostnames are supplied by infrastructure. Examples:
# ALLOWED_HOSTS=rasayam.com,www.rasayam.com,rasayam-alb-123.ap-south-1.elb.amazonaws.com
CONFIGURED_ALLOWED_HOSTS = env_list('ALLOWED_HOSTS')
ALLOWED_HOSTS = CONFIGURED_ALLOWED_HOSTS or ['localhost', '127.0.0.1']

RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

AWS_APP_HOSTNAME = os.getenv('AWS_APP_HOSTNAME')
if AWS_APP_HOSTNAME:
    ALLOWED_HOSTS.append(AWS_APP_HOSTNAME)

ALLOWED_HOSTS = sorted(set(ALLOWED_HOSTS))
if not DEBUG and STRICT_PRODUCTION_ENV and not CONFIGURED_ALLOWED_HOSTS and not RENDER_EXTERNAL_HOSTNAME and not AWS_APP_HOSTNAME:
    raise ValueError('Production requires ALLOWED_HOSTS to include your domain or AWS load balancer hostname.')

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

# AWS load balancers and reverse proxies terminate HTTPS before Gunicorn.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = env_bool('USE_X_FORWARDED_HOST', default=not DEBUG)
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SECURE_REDIRECT_EXEMPT = env_list('SECURE_REDIRECT_EXEMPT', default=[r'^health/$'])
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', default=False)
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')


# Application definition
INSTALLED_APPS = [
    "unfold",  # <--- THIS MUST BE FIRST
    "unfold.contrib.filters",  # For better sidebar filters
    "unfold.contrib.forms",    # For modern form layouts
    "unfold.contrib.import_export",  # For bulk upload feature

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'cloudinary_storage',
    'cloudinary',
    "import_export",
    'storages',

    'products',
]

_MIDDLEWARE_BASE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise is inserted here only when S3 is NOT serving static files.
    # When S3 is active, static requests go directly to the CDN/S3 URL and
    # WhiteNoise would only add overhead scanning the local staticfiles dir.
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Resolved below after S3 config is determined.
MIDDLEWARE = _MIDDLEWARE_BASE

ROOT_URLCONF = 'Rasayam_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # --- Rasayam Custom Processors ---
                'products.context_processors.cart_count', 
            ],
        },
    },
]

WSGI_APPLICATION = 'Rasayam_website.wsgi.application'


# ==========================================
# DATABASE CONFIGURATION
# ==========================================
# Prefer a unified database URL for AWS RDS, Neon, Render, or other managed Postgres.
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.getenv('DB_NAME') and os.getenv('DB_USER'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
            # Connection pooling for high-traffic scenarios
            'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
            'OPTIONS': {
                'connect_timeout': 10,
                'statement_timeout': 30000,  # 30 seconds
            }
        }
    }
else:
    if (
        not DEBUG
        and STRICT_PRODUCTION_ENV
        and not env_bool('ALLOW_SQLITE_IN_PRODUCTION', default=False)
    ):
        raise ValueError('Production requires DATABASE_URL or DB_NAME/DB_USER/DB_HOST for AWS RDS.')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ==========================================
# CACHING CONFIGURATION (High Traffic Optimization)
# ==========================================
# Production uses Redis; Development uses local memory cache
if not DEBUG and os.getenv('REDIS_URL'):
    # Production: Use Redis for distributed caching
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            }
        }
    }
else:
    # Development: Use local memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'rasayam-cache',
            'TIMEOUT': 300,  # 5 minutes default cache timeout
            'OPTIONS': {
                'MAX_ENTRIES': 10000,
            }
        }
    }

# Cache middleware settings for automatic page caching
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = int(os.getenv('CACHE_MIDDLEWARE_SECONDS', '300'))  # 5 minutes

# ==========================================
# QUERY OPTIMIZATION SETTINGS
# ==========================================
# Enable persistent database connections
ATOMIC_REQUESTS = False  # Avoid unnecessary transaction overhead

# Query result caching
if not DEBUG:
    # Log slow queries in production (> 1000ms)
    SLOW_QUERY_THRESHOLD = int(os.getenv('SLOW_QUERY_THRESHOLD', '1000'))
else:
    SLOW_QUERY_THRESHOLD = int(os.getenv('SLOW_QUERY_THRESHOLD', '100'))


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==========================================
# STATIC & MEDIA FILES CONFIGURATION
# ==========================================

STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'

# ── AWS S3 core ──────────────────────────────────────────────────────────────
# Media bucket (required for S3 media uploads)
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
# Static bucket — may be the same bucket as media (files are separated by prefix)
AWS_STATIC_BUCKET_NAME = os.getenv('AWS_STATIC_BUCKET_NAME') or AWS_STORAGE_BUCKET_NAME

AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME') or os.getenv('AWS_DEFAULT_REGION', '')
AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN', '')
AWS_QUERYSTRING_AUTH = env_bool('AWS_QUERYSTRING_AUTH', default=False)
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = os.getenv('AWS_DEFAULT_ACL') or None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': os.getenv('AWS_S3_CACHE_CONTROL', 'max-age=86400, public'),
}
# CORS: space-separated list of allowed origins, e.g. "https://rasayam.com https://www.rasayam.com"
AWS_S3_CORS_ALLOW_ORIGINS = [
    o.strip() for o in os.getenv('AWS_S3_CORS_ALLOW_ORIGINS', '').split() if o.strip()
]

# ── Storage backend resolution ───────────────────────────────────────────────
IS_TESTING = 'test' in sys.argv
_USE_S3_MEDIA = bool(AWS_STORAGE_BUCKET_NAME) and not IS_TESTING
_USE_S3_STATIC = bool(AWS_STATIC_BUCKET_NAME) and not DEBUG and not IS_TESTING

# Cloudinary credentials (kept as fallback when S3 is not configured)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}
_USE_CLOUDINARY = not _USE_S3_MEDIA and all(CLOUDINARY_STORAGE.values())

# ── Static files ─────────────────────────────────────────────────────────────
if _USE_S3_STATIC:
    _static_domain = AWS_S3_CUSTOM_DOMAIN or f'{AWS_STATIC_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    STATIC_URL = f'https://{_static_domain}/static/'
    _STATICFILES_BACKEND = 'Rasayam_website.storages.S3StaticStorage'
else:
    STATIC_URL = '/static/'
    _STATICFILES_BACKEND = (
        'django.contrib.staticfiles.storage.StaticFilesStorage'
        if DEBUG or IS_TESTING
        else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    )
    # Insert WhiteNoise only when it is actually serving static files.
    if not DEBUG and not IS_TESTING:
        MIDDLEWARE = (
            [_MIDDLEWARE_BASE[0], 'whitenoise.middleware.WhiteNoiseMiddleware']
            + _MIDDLEWARE_BASE[1:]
        )

WHITENOISE_MANIFEST_STRICT = False

# ── Media files ───────────────────────────────────────────────────────────────
if _USE_S3_MEDIA:
    _media_domain = AWS_S3_CUSTOM_DOMAIN or f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    MEDIA_URL = f'https://{_media_domain}/media/'
    _MEDIA_BACKEND = 'Rasayam_website.storages.S3MediaStorage'
elif _USE_CLOUDINARY:
    MEDIA_URL = '/media/'
    _MEDIA_BACKEND = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    MEDIA_URL = '/media/'
    _MEDIA_BACKEND = 'django.core.files.storage.FileSystemStorage'

STORAGES = {
    'default': {'BACKEND': _MEDIA_BACKEND},
    'staticfiles': {'BACKEND': _STATICFILES_BACKEND},
}

# ==========================================
# THIRD-PARTY & CUSTOM SETTINGS
# ==========================================

# Razorpay Keys
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET')

LOGIN_URL = 'login'

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "RASAYAM Admin",
    "SITE_HEADER": "RASAYAM Business Portal",
    "SHOW_HISTORY": True,
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False, 
        "navigation": [
            {
                "title": "Marketing & Storefront",
                "items": [
                    {
                        "title": "Banners",
                        "icon": "image", 
                        "link": "/admin/products/banner/",
                    },
                    {
                        "title": "Promo Boxes",
                        "icon": "featured_video",
                        "link": "/admin/products/promobox/",
                    },
                ],
            },
            {
                "title": "Inventory Management",
                "items": [
                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": "/admin/products/product/",
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/products/category/",
                    },
                ],
            },
            {
                "title": "Sales & Support",
                "items": [
                    {
                        "title": "Orders",
                        "icon": "shopping_cart",
                        "link": "/admin/products/order/",
                    },
                    {
                        "title": "Customer Profiles",
                        "icon": "person",
                        "link": "/admin/products/customerprofile/",
                    },
                    {
                        "title": "Contact Inquiries",
                        "icon": "mail",
                        "link": "/admin/products/contactinquiry/",
                    },
                    {
                        "title": "Product Reviews",
                        "icon": "star",
                        "link": "/admin/products/review/",
                    },
                ],
            },
        ],
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.server': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

if not DEBUG and STRICT_PRODUCTION_ENV:
    required_production_env = {
        'RAZORPAY_KEY_ID': RAZORPAY_KEY_ID,
        'RAZORPAY_KEY_SECRET': RAZORPAY_KEY_SECRET,
    }
    missing_production_env = [
        key for key, value in required_production_env.items()
        if not value
    ]
    if missing_production_env:
        raise ValueError(f"Production requires: {', '.join(missing_production_env)}")

# Additional validation for Razorpay keys in all production environments
# (Solved by Claude: Added startup validation to catch missing payment gateway credentials early)
if not DEBUG and not RAZORPAY_KEY_ID:
    import warnings
    warnings.warn("WARNING: RAZORPAY_KEY_ID is not set. Payment verification will fail in production.", RuntimeWarning)
    
if not DEBUG and not RAZORPAY_KEY_SECRET:
    import warnings
    warnings.warn("WARNING: RAZORPAY_KEY_SECRET is not set. Payment processing will fail in production.", RuntimeWarning)

# Zavu Integration
ZAVUDEV_API_KEY = os.getenv('ZAVUDEV_API_KEY', '')
