# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cartitem_price_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_cart_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
