# Generated by Django 6.0.3 on 2026-06-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='banner',
            name='banner_active_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cartitem_cart_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='customer_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='customer_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_razorpay_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_is_paid_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_seller_tag_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='productimage_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='promobox',
            name='promobox_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_product_verified_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name for SEO-friendly URLs', null=True, unique=True),
        ),
    ]
