# Generated by Django 6.0.3 on 2026-08-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_customerprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
