# Generated by Django 6.0.3 on 2026-09-24 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_remove_customerprofile_phone_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delhivery_shipment_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Last known Delhivery tracking status",
                max_length=100,
                verbose_name="Shipment Status",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delhivery_waybill",
            field=models.CharField(
                blank=True,
                help_text="Waybill number assigned by Delhivery",
                max_length=100,
                null=True,
                verbose_name="Delhivery Waybill",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="Full Name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                ("pincode", models.CharField(max_length=6, verbose_name="PIN Code")),
                (
                    "address_line1",
                    models.CharField(
                        max_length=255, verbose_name="Flat / House No / Building"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        max_length=255, verbose_name="Area / Street / Locality"
                    ),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Landmark"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City / Town")),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("WORK", "Office / Work"),
                            ("OTHER", "Other"),
                        ],
                        default="HOME",
                        max_length=10,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default address"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
    ]
